### ISSUE TITLE
Restrictinf xml file size

### ISSUE THREAD

**Issue by girisubhra** [MicroOps-cn/data_exporter#10]
I want to read the xml file whose size is above 600 bytes. so i modifed code as below, but it is not giving expected result. can you please suggest on this.
File name : datasource.go
------------------------------
func (d *Datasource) ReadAll(ctx context.Context) ([]byte, error) {
	var reader io.Reader
	rc, err := d.GetStream(ctx)
	if err != nil {
		return nil, err
	}
	defer rc.Close()
	reader = io.LimitReader(rc, *d.MaxContentLength)
        **if reader > 600 {
	          return ioutil.ReadAll(reader)
       }**
}

**Comment by MicroOps-cn** [comment]
Are you sure it is 600 bytes?
The XML file in the example "examples/xml_3gpp_ts /" is 2.86 KB. 600 bytes must be OK.

**Comment by MicroOps-cn** [comment]
https://github.com/MicroOps-cn/data_exporter/blob/b0e93f972608effe12772d615d7f3dcd6427a41f/collector/datasource.go#L191
https://github.com/MicroOps-cn/data_exporter/blob/b0e93f972608effe12772d615d7f3dcd6427a41f/collector/datasource.go#L268-L277

The size limit for file reading is set by `max_content_length` is controlled by the configuration parameter. If it is not specified, the default value is 102400000bytes (about 100MB)

It is also described in the document:
https://github.com/MicroOps-cn/data_exporter/blob/master/README-en.md#file
```yaml
datasource:
  - type: "file"
    name: <string> # datasource name 
    max_content_length: <int> # The maximum read length, in bytes, When the value of "read_mode" is stream, it defaults to 0 (unlimited),otherwise the default value is 102400000  
    line_max_content_length: <int> # The maximum read length per line,in bytes,0 means unlimited, defaults: 102400000
    
    relabel_configs: [ <relabel_config>, ... ] # reference: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
    timeout: <duration>  # The default is "30s", which cannot be less than "1ms", reference: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#duration
    read_mode: <string> # read mode, The value can be: "stream","line" or "full", defaults: "full"
    url: "../examples/weather.xml"
    line_separator: [<string>,...] # The value can be string、[string,...], Line separator, default: "\n"
    end_of: # Message end flag. When this flag is read, it will stop reading and close the connection. The message is line buffered, so The end_of value of cannot be multiple rows.
```
