### ISSUE TITLE
如何动态更改datasource的url地址？

### ISSUE THREAD

**Issue by qwzhou89** [MicroOps-cn/data_exporter#3]
```yaml
collects:
  - name: "test-http"
    relabel_configs: [ ]
    data_format: "json" # 原数据格式/数据匹配模式
    datasource:
      - type: "file"
        url: "../examples/my_data.json"
      - type: "http"
        url: "https://localhost/examples/my_data.json"
        relabel_configs: [ ]
    metrics: # metric 匹配规则
      - name: "Point1"
        relabel_configs: # 根据匹配到数据及标签，进行二次处理，和Prometheus的relabel_configs用法一致
          - source_labels: [ __name__ ]
            target_label: name
```
datasource里面的relabel_configs是否有能力根据调用参数改变当前datasource的url？
我们在Prometheus里面使用blackbox exporter时，通过使用下面的relabelling，最终探测的是http://prometheus.io、https://prometheus.io、http://example.com:8080 这些targets的黑盒指标，在data_exporter里面该如何动态修改这个datasource的url呢？

```yaml
scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
        - http://example.com:8080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
```
