### ISSUE TITLE
http类型的带header和body的请求，不能正常获得返回值

### ISSUE THREAD

**Issue by qwzhou89** [MicroOps-cn/data_exporter#4]
```yaml
    datasource:
      - type: "http"
        name: "eth_node"
        relabel_configs: []
        url: "https://bsc-dataseed2.binance.org"
        config:
          body: '{"id":1, "jsonrpc":"2.0", "method": "eth_blockNumber"}' # HTTP请求报文
          headers: { "Content-Type": "application/json"} # 自定义HTTP头
          method: 'POST' #HTTP请求方法 GET/POST/PUT...
```
像这样的datasource配置，不能获取到json数据
