### ISSUE TITLE
XML data extraction

### ISSUE THREAD

**Issue by girisubhra** [MicroOps-cn/data_exporter#8]
I am sending my pmdata.xml file and data_exporter.yaml in attachment,

<-------------------------->
<measValue measObjLdn="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-31">
            <measResults>101 200 300 90 30</measResults>
         </measValue>
files.zip](https://github.com/MicroOps-cn/data_exporter/files/9007573/files.zip)

<------------------------>
I have to extract each values from measResults from the able shown values from pmdata.xml file ,i,e
101
200
300
90
30 
Please help how to extract value like this.

**Comment by MicroOps-cn** [comment]
How to distinguish these values in the indicator? 
For example, add an index to label, such as
```
meas_value{idx="0"} 101
meas_value{idx="1"} 200
meas_value{idx="2"} 300
```
Or add a suffix to metric_name, such as:
```
meas_value_0{} 101
meas_value_1{} 200
meas_value_2{} 300
```

**Comment by MicroOps-cn** [comment]
It seems that the current logic can not implement your requirements in a friendly way. Only each value of measresults can be generated and configured separately
```
collects:
  - name: "meas_info"
    data_format: "xml"
    datasource:
      - type: "file"
        url: "pmdata.xml"
    metrics:
      - name: "meas_info"
        match:
          datapoint: "//measData/measInfo/measValue/measResults"
          labels:
            __value__: '{{ .Text|reReplaceAll "^([0-9]+).+$" "$1" }}'
            name: '{{ ((.FindElement "../").SelectAttr "measObjLdn").Value }}'
            meas_info_id: '{{ ((.FindElement "../../").SelectAttr "measInfoId").Value }}'
            # Suppose the value of "begintime" is the real time when the monitoring data is generated
            __time__: '{{ ((.FindElement "../../../../fileHeader/measCollec").SelectAttr "beginTime").Value }}'
            index: 0
      - name: "meas_info"
        match:
          datapoint: "//measData/measInfo/measValue/measResults"
          labels:
            __value__: '{{ .Text|reReplaceAll "^[0-9]+ ([0-9]+).+$" "$1" }}'
            name: '{{ ((.FindElement "../").SelectAttr "measObjLdn").Value }}'
            meas_info_id: '{{ ((.FindElement "../../").SelectAttr "measInfoId").Value }}'
            index: 1
      - name: "meas_info"
        match:
          datapoint: "//measData/measInfo/measValue/measResults"
          labels:
            __value__: '{{ .Text|reReplaceAll "^(?:[0-9]+ ){2}([0-9]+).+$" "$1" }}'
            name: '{{ ((.FindElement "../").SelectAttr "measObjLdn").Value }}'
            meas_info_id: '{{ ((.FindElement "../../").SelectAttr "measInfoId").Value }}'
            index: 2
      - name: "meas_info"
        match:
          datapoint: "//measData/measInfo/measValue/measResults"
          labels:
            __value__: '{{ .Text|reReplaceAll "^(?:[0-9]+ ){3}([0-9]+).+$" "$1" }}'
            name: '{{ ((.FindElement "../").SelectAttr "measObjLdn").Value }}'
            meas_info_id: '{{ ((.FindElement "../../").SelectAttr "measInfoId").Value }}'
            index: 3
      - name: "meas_info"
        match:
          datapoint: "//measData/measInfo/measValue/measResults"
          labels:
            __value__: '{{ .Text|reReplaceAll "^(?:[0-9]+ ){4}([0-9]+).+$" "$1" }}'
            name: '{{ ((.FindElement "../").SelectAttr "measObjLdn").Value }}'
            meas_info_id: '{{ ((.FindElement "../../").SelectAttr "measInfoId").Value }}'
            index: 4
      - name: "meas_info"
        match:
          datapoint: "//measData/measInfo/measValue/measResults"
          labels:
            __value__: '{{ .Text|reReplaceAll "^(?:[0-9]+ ){5}([0-9]+).+$" "$1" }}'
            name: '{{ ((.FindElement "../").SelectAttr "measObjLdn").Value }}'
            meas_info_id: '{{ ((.FindElement "../../").SelectAttr "measInfoId").Value }}'
            index: 5
```
The results are as follows:
```
meas_info{index="0",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-11"} 10 1647511200000
meas_info{index="0",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-21"} 11 1647511200000
meas_info{index="0",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-31"} 101 1647511200000
meas_info{index="0",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-11"} 1 1647511200000
meas_info{index="0",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-21"} 9 1647511200000
meas_info{index="0",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-31"} 6 1647511200000
meas_info{index="0",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-11"} 60 1647511200000
meas_info{index="0",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-21"} 50 1647511200000
meas_info{index="0",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-31"} 10 1647511200000
meas_info{index="0",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-11"} 10 1647511200000
meas_info{index="0",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-21"} 90 1647511200000
meas_info{index="0",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-31"} 40 1647511200000
meas_info{index="1",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-11"} 20
meas_info{index="1",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-21"} 12
meas_info{index="1",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-31"} 200
meas_info{index="1",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-11"} 2
meas_info{index="1",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-21"} 8
meas_info{index="1",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-31"} 7
meas_info{index="1",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-11"} 70
meas_info{index="1",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-21"} 40
meas_info{index="1",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-31"} 20
meas_info{index="1",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-11"} 20
meas_info{index="1",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-21"} 20
meas_info{index="1",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-31"} 30
meas_info{index="2",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-11"} 30
meas_info{index="2",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-21"} 13
meas_info{index="2",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-31"} 300
meas_info{index="2",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-11"} 3
meas_info{index="2",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-21"} 7
meas_info{index="2",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-31"} 8
meas_info{index="2",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-11"} 80
meas_info{index="2",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-21"} 30
meas_info{index="2",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-31"} 30
meas_info{index="2",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-11"} 20
meas_info{index="2",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-21"} 30
meas_info{index="2",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-31"} 20
meas_info{index="3",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-11"} 40
meas_info{index="3",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-21"} 14
meas_info{index="3",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-31"} 90
meas_info{index="3",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-11"} 4
meas_info{index="3",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-21"} 6
meas_info{index="3",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-31"} 9
meas_info{index="3",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-11"} 9
meas_info{index="3",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-21"} 2
meas_info{index="3",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-31"} 4
meas_info{index="3",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-11"} 3
meas_info{index="3",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-21"} 1
meas_info{index="3",meas_info_id="RRC",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-31"} 1
meas_info{index="4",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-11"} 5
meas_info{index="4",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-21"} 1
meas_info{index="4",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL08-123456-31"} 3
meas_info{index="4",meas_info_id="FDDL",name="ENBFunction=ORAN-XXXX-TB,EUtranCellFDD=TL21-123456-31"} 1
```
